### ISSUE TITLE
Module not found: Error: Package path . is not exported from package ...node_modules/svelte-agnostic-draggable

### ISSUE THREAD

**Issue by gosixl** [rozek/svelte-agnostic-draggable#6]
I get this issue when compiling with webpack (svelte-loader).

I solved by adding this to exports in package.json:
`    ".": "./dist/svelte-agnostic-draggable.esm.js"`

so my package.json looks as follows
`{
  "name": "svelte-agnostic-draggable",
  "version": "0.1.12",
  "description": "jQuery UI interactions draggable/droppable/sortable for Svelte",
  "module": "./dist/svelte-agnostic-draggable.esm.js",
  "svelte": "./dist/svelte-agnostic-draggable.esm.js",
  "types": "./dist/svelte-agnostic-draggable.d.ts",
  "exports": {
    "./package.json": "./package.json",
    ".": "./dist/svelte-agnostic-draggable.esm.js"
  },
  "scripts": {
    "build": "rimraf dist && rollup -c rollup.config.js && tsc && mv src/*.d.ts dist && rm src/*.js*",
    "agadoo": "agadoo ./dist/svelte-agnostic-draggable.esm.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/rozek/svelte-agnostic-draggable.git"
  },
  "keywords": [
    "svelte3",
    "svelte-action",
    "jquery-ui",
    "draggable",
    "droppable",
    "sortable"
  ],
  "author": "Andreas Rozek <a.rozek@gmx.de> (https://www.rozek.de/)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/rozek/svelte-agnostic-draggable/issues"
  },
  "homepage": "https://github.com/rozek/svelte-agnostic-draggable#readme",
  "dependencies": {
    "agnostic-draggable-bug-fixed": "^1.0.13"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^19.0.0",
    "@rollup/plugin-node-resolve": "^13.0.0",
    "@rollup/plugin-typescript": "^8.2.1",
    "agadoo": "^2.0.0",
    "rimraf": "^3.0.2",
    "rollup": "^2.51.2",
    "rollup-plugin-terser": "^7.0.2",
    "typescript": "^4.3.2"
  }
}
`

**Comment by rozek** [comment]
Thank you very much for this notice and the solution - I just updated my `package.json` accordingly

**Comment by gosixl** [comment]
No problem!On 15 Jan 2023, at 05:21, Andreas Rozek ***@***.***> wrote:﻿
Thank you very much for this notice and the solution - I just updated my package.json accordingly
