### ISSUE TITLE
Droppable option accept function triggers every time position of the draggable is changed over it

### ISSUE THREAD

**Issue by andreiciobanica** [rozek/svelte-agnostic-draggable#8]
When you have

`<div use:droppable={{ accept: function (d){ console.log(d);}, }}>Drop here</div>`

every time you move the `draggable div` on `droppable div` it triggers the `accept function`.

**Comment by rozek** [comment]
well, as you mentioned in another [issue](https://github.com/marcospont/agnostic-draggable/issues/15), this problem has to be solved by [agnostic-draggable](https://github.com/marcospont/agnostic-draggable) itself.

Once that is done, I may just rebuilt this module and everything works as intended again.
